# Generated by Django 4.0 on 2023-10-11 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_dayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentd',
            name='user',
        ),
        migrations.DeleteModel(
            name='Dayment',
        ),
        migrations.DeleteModel(
            name='PaymentD',
        ),
    ]
